// Generated by Actions sync workflow — do not edit by hand.
window.NIJSTERS_SUPABASE = Object.freeze({
  url:     "https://rvkveuvrchzainwwfmem.supabase.co",
  anonKey: "sb_publishable_muSm2SaqJmZQjpUak7j2fQ_ljhn0a3O",
});
